# Generated by Django 4.1.4 on 2022-12-14 21:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_application_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='submitdate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
