# Generated by Django 4.1.4 on 2022-12-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_application_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='submitdate',
            field=models.DateField(),
        ),
    ]
