# Generated by Django 4.1.4 on 2022-12-14 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_application_submitdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='submitdate',
        ),
    ]
