# Generated by Django 4.1.4 on 2022-12-14 21:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_application_submitdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='submitdate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
