# Generated by Django 4.1.4 on 2022-12-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_submitdate_application_submit_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(choices=[('VS', 'Visa'), ('PP', 'Passport')], default='VS', max_length=100),
        ),
    ]
