# Generated by Django 4.1.4 on 2022-12-16 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_application_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='name',
            new_name='type',
        ),
    ]
