# Generated by Django 4.1.4 on 2022-12-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_name_application_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='type',
            field=models.CharField(choices=[('Visa', 'Visa'), ('Passport', 'Passport')], default='Visa', max_length=100),
        ),
    ]
